In [1]:
import xarray as xr
import numpy as np
import pandas as pd
from datetime import date
today = date.today()
import re

In [2]:
# Read the Excel file into a pandas DataFrame
data = pd.read_csv('SD1053_T_S_DO_final2.txt',delimiter='\t', header=0)
data=data.fillna(-999999)
data

,Platform,Date-Time,Longitude,Latitude,Depth_m,T_SBE_degC,S_SBE_corr,DO_SBE_raw_umol/L,DO_SBE_corr_umol/L,DO_SBE_corr_saturation_%,Press_atm_hpa,T_air_degC
0,SD1053,18.10.2019 11:00,-15.330453,27.975040,0.5,22.5733,36.440,217.01,218.86,100.31,1020.91,22.27
1,SD1053,18.10.2019 12:00,-15.293437,27.938038,0.5,22.6462,36.523,216.15,217.60,99.91,1020.32,22.35
2,SD1053,18.10.2019 13:00,-15.268942,27.893526,0.5,22.6542,36.536,216.15,217.55,99.91,1019.68,22.40
3,SD1053,18.10.2019 14:00,-15.304269,27.848787,0.5,22.4781,36.477,217.75,219.49,100.45,1018.92,22.23
4,SD1053,18.10.2019 15:00,-15.329208,27.802470,0.5,22.4513,36.433,217.98,219.91,100.57,1018.06,22.25
...,...,...,...,...,...,...,...,...,...,...,...,...
6550,SD1053,17.07.2020 09:00,13.703283,45.694890,0.5,21.5026,36.499,-999999.00,-999999.00,-999999.00,1013.58,22.15
6551,SD1053,17.07.2020 10:00,13.707722,45.692394,0.5,21.5904,36.698,-999999.00,-999999.00,-999999.00,1013.73,22.75
6552,SD1053,17.07.2020 11:00,13.701947,45.695325,0.5,21.6926,36.706,-999999.00,-999999.00,-999999.00,1014.33,23.19
6553,SD1053,17.07.2020 12:00,13.705694,45.692259,0.5,21.6247,36.642,-999999.00,-999999.00,-999999.00,1014.12,23.45
6554,SD1053,17.07.2020 13:00,13.701253,45.696090,0.5,21.7699,36.590,-999999.00,-999999.00,-999999.00,1014.06,23.87

In [3]:
# Iterate over each column in the DataFrame

data.columns = [re.sub(r'[-%/ ]', '_', col) for col in data.columns]

for column in data.columns:
    # Convert the column to a NumPy array
    np_array = data[column].to_numpy()
    
    # Convert the data type to int32 or float32
    if np_array.dtype == 'int64':
        np_array = np_array.astype('int32')
    elif np_array.dtype == 'float64':
        np_array = np_array.astype('float32')
    
    # Delete the old NumPy array if it exists
    if column in locals():
        del locals()[column]
    
    # Use the modified column name as the variable name
    globals()[column] = np_array

In [4]:
time_a=Date_Time
Lat_a=Latitude
Lon_a=Longitude

Air_Temp_a= T_air_degC

Platform_a=Platform

Press_a= Press_atm_hpa

DO_a= DO_SBE_corr_umol_L
DOsat_a= DO_SBE_corr_saturation__
Depth_a= Depth_m
Salinity_a=S_SBE_corr_
Temperature_a=T_SBE_degC

In [5]:
# Read the Excel file into a pandas DataFrame
data = pd.read_csv('SD1030_T_S_DO_CO2_final2.txt',delimiter='\t', header=0)
data=data.fillna(-999999)

# Iterate over each column in the DataFrame

data.columns = [re.sub(r'[-%/ ]', '_', col) for col in data.columns]

for column in data.columns:
    # Convert the column to a NumPy array
    np_array = data[column].to_numpy()
    
    # Convert the data type to int32 or float32
    if np_array.dtype == 'int64':
        np_array = np_array.astype('int32')
    elif np_array.dtype == 'float64':
        np_array = np_array.astype('float32')
    
    # Delete the old NumPy array if it exists
    if column in locals():
        del locals()[column]
    
    # Use the modified column name as the variable name
    globals()[column] = np_array

In [6]:
whos

Variable                     Type         Data/Info
---------------------------------------------------
Air_Temp_a                   ndarray      6555: 6555 elems, type `float32`, 26220 bytes
DO_SBE_corr_saturation__     ndarray      6555: 6555 elems, type `float32`, 26220 bytes
DO_SBE_corr_umol_L           ndarray      6555: 6555 elems, type `float32`, 26220 bytes
DO_SBE_raw_umol_L            ndarray      6555: 6555 elems, type `float32`, 26220 bytes
DO_a                         ndarray      6555: 6555 elems, type `float32`, 26220 bytes
DOsat_a                      ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Date_Time                    ndarray      6555: 6555 elems, type `object`, 52440 bytes
Depth_a                      ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Depth_m                      ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Lat_a                        ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Latitude                     ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Lon_a                        ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Longitude                    ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Platform                     ndarray      6555: 6555 elems, type `object`, 52440 bytes
Platform_a                   ndarray      6555: 6555 elems, type `object`, 52440 bytes
Press_a                      ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Press_atm_LiCor_hPA          ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Press_atm_hpa                ndarray      6555: 6555 elems, type `float32`, 26220 bytes
S_SBE_corr_                  ndarray      6555: 6555 elems, type `object`, 52440 bytes
S_SBE_raw                    ndarray      6555: 6555 elems, type `object`, 52440 bytes
Salinity_a                   ndarray      6555: 6555 elems, type `float32`, 26220 bytes
T_SBE_degC                   ndarray      6555: 6555 elems, type `object`, 52440 bytes
T_air_degC                   ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Temperature_a                ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Unnamed:_17                  ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Unnamed:_18                  ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Unnamed:_19                  ndarray      6555: 6555 elems, type `float32`, 26220 bytes
column                       str          Unnamed:_19
data                         DataFrame         Platform         Dat<...>n[6555 rows x 20 columns]
date                         type         <class 'datetime.date'>
np                           module       <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
np_array                     ndarray      6555: 6555 elems, type `float32`, 26220 bytes
pCO2_sea_wet_corr_uatm       ndarray      6555: 6555 elems, type `float32`, 26220 bytes
pd                           module       <module 'pandas' from '/h<...>ages/pandas/__init__.py'>
re                           module       <module 're' from '/home/<...>da3/lib/python3.9/re.py'>
time_a                       ndarray      6555: 6555 elems, type `object`, 52440 bytes
today                        date         2023-11-01
xCO2_air_dry_corr_umol_mol   ndarray      6555: 6555 elems, type `float32`, 26220 bytes
xCO2_sea_dry_corr_umol_mol   ndarray      6555: 6555 elems, type `float32`, 26220 bytes
xr                           module       <module 'xarray' from '/h<...>ages/xarray/__init__.py'>

In [7]:
time=Date_Time
Lat_b=Latitude
Lon_b=Longitude

Depth_b=Depth_m
DO_b= DO_SBE_corr_umol_L
DOsat_b= DO_SBE_corr_saturation__
Salinity_b=S_SBE_corr_
Temperature_b=T_SBE_degC


Air_Temp_b= T_air_degC
Press_b= Press_atm_hpa
Press_atm_LiCor_hPA=Press_atm_LiCor_hPA

xCO2_air_dry_corr_umol_mol=xCO2_air_dry_corr_umol_mol
xCO2_sea_dry_corr_umol_mol=xCO2_sea_dry_corr_umol_mol

In [11]:
ds=xr.Dataset(
    data_vars=dict(
        
       
        Oxygen_1053=(["time"], DO_a,{"units": "umol/L",
                                            "standard_name": "mole_concentration_of_dissolved_molecular_oxygen_in_sea_water",
                                            "short_name": "DO",
                                            "long_name": "mole_concentration_of_dissolved_molecular_oxygen_in_sea_water",
                                            "description": "Molarity of dissolved Oxygen in sea water measured by SBE37-SMP-ODO ",
                                            "valid_min": "0",
                                            "valid_max": "400",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        DO_sat_1053=(["time"], DOsat_a,{"units": "uatm",
                                            "standard_name": "dissolved_molecular_oxygen_saturation_in_sea_water",
                                            "short_name": "DOsat",
                                            "long_name": "dissolved_molecular_oxygen_saturation_in_sea_water",
                                            "description": "Dissolved Oxygen saturation in sea water measured by SBE37-SMP-ODO.",
                                            "valid_min": "0",
                                            "valid_max": "400",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        
        
        Depth_1053=(["time"], Depth_a,{"units": "m",
                                            "standard_name": "depth",
                                            "short_name": "depth",
                                            "long_name": "depth",
                                            "description": "depth from where the water sample is collected (m)",
                                            "valid_min": "0",
                                            "valid_max": "10000",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
    
        air_temperature_1053=(["time"], Air_Temp_a,{"units": "K",
                                            "standard_name": "air_temperature",
                                            "short_name": "Temp",
                                            "long_name": "Temperature",
                                            "description": "Air temperature is the bulk temperature of the air",
                                            "valid_min": "-273",
                                            "valid_max": "500",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        Press_1053=(["time"], Press_a,{"units": "hPa",
                                            "standard_name": "atmospheric_pressure",
                                            "short_name": "atm_press",
                                            "long_name": "Atmospheric Pressure",
                                            "description": "Atmospheric Pressure",
                                            "valid_min": "0",
                                            "valid_max": "10000",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        

        Salinity_1053=(["time"], Salinity_a,{"units": "psu",
                                            "standard_name": "sea_water_salinity",
                                            "short_name": "so",
                                            "long_name": "Sea Water Salinity",
                                            "description": "Sea water salinity is the salt content of sea water on the Practical Salinity Scale, measured by SBE37 deployed from the research vessel",
                                            "valid_min": "0",
                                            "valid_max": "100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": "uncorrected"}),

        Temperature_1053=(["time"], Temperature_a,{"units": "degree Celcius",
                                            "standard_name": "sea_water_temperature",
                                            "short_name": "SW_Temperature",
                                            "long_name": "Sea Water Temperature",
                                            "description": "Sea water temperature is the in situ temperature of the sea water measured by the SBE37-SMP-ODO",
                                            "valid_min": "-10",
                                            "valid_max": "100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
     
  #Here it starts the 1030
        
        Oxygen_1030=(["time"], DO_b,{"units": "umol/L",
                                            "standard_name": "mole_concentration_of_dissolved_molecular_oxygen_in_sea_water",
                                            "short_name": "DO",
                                            "long_name": "mole_concentration_of_dissolved_molecular_oxygen_in_sea_water",
                                            "description": "Molarity of dissolved Oxygen in sea water measured by SBE37-SMP-ODO ",
                                            "valid_min": "0",
                                            "valid_max": "400",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        DO_sat_1030=(["time"], DOsat_b,{"units": "uatm",
                                            "standard_name": "dissolved_molecular_oxygen_saturation_in_sea_water",
                                            "short_name": "DOsat",
                                            "long_name": "dissolved_molecular_oxygen_saturation_in_sea_water",
                                            "description": "Dissolved Oxygen saturation in sea water measured by SBE37-SMP-ODO.",
                                            "valid_min": "0",
                                            "valid_max": "400",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        
        
        Depth_1030=(["time"], Depth_b,{"units": "m",
                                            "standard_name": "depth",
                                            "short_name": "depth",
                                            "long_name": "depth",
                                            "description": "depth from where the water sample is collected (m)",
                                            "valid_min": "0",
                                            "valid_max": "10000",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
    
        air_temperature_1030=(["time"], Air_Temp_b,{"units": "K",
                                            "standard_name": "air_temperature",
                                            "short_name": "Temp",
                                            "long_name": "Temperature",
                                            "description": "Air temperature is the bulk temperature of the air",
                                            "valid_min": "-273",
                                            "valid_max": "500",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        Press_1030=(["time"], Press_b,{"units": "hPa",
                                            "standard_name": "atmospheric_pressure",
                                            "short_name": "atm_press",
                                            "long_name": "Atmospheric Pressure",
                                            "description": "Atmospheric Pressure",
                                            "valid_min": "0",
                                            "valid_max": "10000",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        Press_LICOR_1030=(["time"], Press_atm_LiCor_hPA,{"units": "hPa",
                                            "standard_name": "atmospheric_pressure",
                                            "short_name": "atm_press",
                                            "long_name": "Atmospheric Pressure",
                                            "description": "Atmospheric Pressure",
                                            "valid_min": "0",
                                            "valid_max": "10000",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        

        Salinity_1030=(["time"], Salinity_b,{"units": "psu",
                                            "standard_name": "sea_water_salinity",
                                            "short_name": "so",
                                            "long_name": "Sea Water Salinity",
                                            "description": "Sea water salinity is the salt content of sea water on the Practical Salinity Scale, measured by SBE37 deployed from the research vessel",
                                            "valid_min": "0",
                                            "valid_max": "100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": "uncorrected"}),

        Temperature_1030=(["time"], Temperature_b,{"units": "degree Celcius",
                                            "standard_name": "sea_water_temperature",
                                            "short_name": "SW_Temperature",
                                            "long_name": "Sea Water Temperature",
                                            "description": "Sea water temperature is the in situ temperature of the sea water measured by the SBE37-SMP-ODO",
                                            "valid_min": "-10",
                                            "valid_max": "100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
                
        xCO2_air=(["time"], xCO2_air_dry_corr_umol_mol,{"units": "umol mol-1",
                                            "standard_name": "surface_partial_pressure_of_carbon_dioxide_in_air",
                                            "short_name": "pCO2",
                                            "long_name": "Surface partial pressure of carbon dioxide in air",
                                            "description": "pCO2 in air",
                                            "valid_min": "0",
                                            "valid_max": "400",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        xCO2_sea=(["time"], xCO2_sea_dry_corr_umol_mol,{"units": "umol mol-1",
                                            "standard_name": "surface_partial_pressure_of_carbon_dioxide_in_sea_water",
                                            "short_name": "pCO2",
                                            "long_name": "Surface partial pressure of carbon dioxide in sea water",
                                            "description": "pCO2 in water",
                                            "valid_min": "0",
                                            "valid_max": "400",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        

    ),
    coords=dict(
    lon_1053=(["lon_1053"], Lon_a,{"units": "degrees East",
                                        "standard_name": "longitude",
                                        "short_name": "lon",
                                        "long_name": "Longitude",
                                        "description": "The Longitude represents the degrees east",
                                        "valid_min": "0",
                                        "valid_max": "360",
                                        "missing_value": "-9999999",
                                        "history": ""}),
                       
    lat_1053=(["lat_1053"], Lat_a,{"units": "degrees North",
                                        "standard_name": "latitude",
                                        "short_name": "lat",
                                        "long_name": "Latitude",
                                        "description": "The latitude represents the degrees north",
                                        "valid_min": "-90",
                                        "valid_max": "90",
                                        "missing_value": "-9999999",
                                        "history": ""}),
    lon_1030=(["lon_1030"], Lon_b,{"units": "degrees East",
                                        "standard_name": "longitude",
                                        "short_name": "lon",
                                        "long_name": "Longitude",
                                        "description": "The Longitude represents the degrees east",
                                        "valid_min": "0",
                                        "valid_max": "360",
                                        "missing_value": "-9999999",
                                        "history": ""}),
                       
    lat_1030=(["lat_1030"], Lat_b,{"units": "degrees North",
                                        "standard_name": "latitude",
                                        "short_name": "lat",
                                        "long_name": "Latitude",
                                        "description": "The latitude represents the degrees north",
                                        "valid_min": "-90",
                                        "valid_max": "90",
                                        "missing_value": "-9999999",
                                        "history": ""}),
    time=time,
    reference_time=time[0],
)
)

In [14]:


ds.attrs['id']='DOI needed'

ds.attrs['naming_authority']='NORCE Norwegian Research Centre (Norway),Istituto Nazionale di Oceanografia e Geofisica Sperimentale (Italy),Consiglio Nazionale delle Ricerche - Istituto di scienze marine (Italy),Consiglio Nazionale delle Ricerche - Istituto per lo studio degli impatti Antropici e SostenibilitÃ  in ambiente marino (Italy),Laboratoire OcÃ©anographique de Villefranche/French National Centre for Scientific Research (France),GEOMAR Helmholtz Centre for Ocean Research Kiel (Germany) '

ds.attrs['title'] = "SD1053"

ds.attrs['summary']='SD1053 is an Autonomous Surface Vehicle (ASV) provided by the US company Saildrone. The SD1053 took part in the ATL2MED demonstration experiment from October 2019 to July 2020. During this time, the SD1053 equipped with scientific instruments sailed from the North-East Atlantic Ocean to the Gulf of Trieste in the Mediterranean Sea. A number of fixed ocean stations also took part in the experiment, e.g., DYFAMED, W1M3A, E2M3A, PALOMA, and MIRAMARE. A second ASV, SD1030, also took part in the demonstration experiment.'

ds.attrs['keywords']='Meteorology, Hydrography'
ds.attrs['keywords_vocabulary']='Temperature, Air pressure, Relative Humidity, Wind speed, Wind Direction'

ds.attrs['geospatial_lat_min']=np.min(Lat_a)
ds.attrs['geospatial_lat_max']=np.max(Lat_a)
ds.attrs['geospatial_lon_miN']=np.min(Lon_a)
ds.attrs['geospatial_lon_max']=np.max(Lon_a)

ds.attrs['time_coverage_start']=str(np.min(time_a))
ds.attrs['time_coverage_end']=str(np.max(time_a))

ds.attrs['Conventions']='CF 1.14'

ds.attrs['processing_level']='LEVEL 2'

ds.attrs['date_created']=str(today)

ds.attrs['creator_type']='Group'
ds.attrs['creator_institution']='Geophysical Institute'
ds.attrs['creator_name']='Joan Mateu Horrach Pou'
ds.attrs['creator_email']='joan.pou@uib.no'
ds.attrs['creator_url']=''

ds.attrs['institution']='Geophysical Institute'

ds.attrs['publisher_name']='Joan Mateu Horrach Pou'
ds.attrs['publisher_email']='joan.pou@uib.no'
ds.attrs['publisher_url']='I need the url'

ds.attrs['project']='ICOS'

ds.attrs['platform']='SD1053'
ds.attrs['platform_vocabulary']='Saildrone Autonomous Surface Vehicle'

ds.attrs['instrument']='Saildrone, SBE37-SMP-ODO'

ds.attrs['iso_topic_category']='Needed'
ds.attrs['activity_type']='in situ observation'
ds.attrs['operational_status']='active'

In [21]:
comp = dict(zlib=True, complevel=6)  # Adjust complevel as needed
encoding = {var: comp for var in ds.data_vars}
ds.to_netcdf('SD_1053.nc', encoding=encoding)

TypeError: expected bytes, int found