In [1]:
import xarray as xr
import numpy as np
import pandas as pd
from datetime import date
today = date.today()
import re

In [2]:
# Read the Excel file into a pandas DataFrame
data_ctd = pd.read_excel('PALOMA_auxiliary_CTD.xlsx', header=0)
data_ctd

,Fixed_Station,YYYY-MM-DD hh:mm:ss,Longitude,Latitude,Depth_dbar,T_SBE37_degC,S_SBE37
0,PALOMA,2020-07-15 11:41:09,13.5658,45.6204,0.633,22.5441,37.1831
1,PALOMA,2020-07-15 11:42:09,13.5658,45.6204,0.660,22.4708,36.9997
2,PALOMA,2020-07-15 11:43:09,13.5658,45.6204,0.692,22.5128,36.9330
3,PALOMA,2020-07-15 11:44:09,13.5658,45.6204,0.917,22.3996,36.9347
4,PALOMA,2020-07-15 11:45:09,13.5658,45.6204,0.744,22.5016,36.8353
...,...,...,...,...,...,...,...
314,PALOMA,2020-07-15 17:28:09,13.5658,45.6204,0.590,22.5488,36.9773
315,PALOMA,2020-07-15 17:29:09,13.5658,45.6204,0.650,22.5478,36.9784
316,PALOMA,2020-07-15 17:30:09,13.5658,45.6204,0.596,22.5483,36.9817
317,PALOMA,2020-07-15 17:31:09,13.5658,45.6204,0.589,22.5361,36.9848
318,PALOMA,2020-07-15 17:32:09,13.5658,45.6204,0.616,22.5443,36.9861

In [4]:
# Iterate over each column in the DataFrame

data_ctd.columns = [re.sub(r'[-%/: ]', '_', col) for col in data_ctd.columns]

for column in data_ctd.columns:
    # Convert the column to a NumPy array
    np_array = data_ctd[column].to_numpy()
    
    # Convert the data type to int32 or float32
    if np_array.dtype == 'int64':
        np_array = np_array.astype('int32')
    elif np_array.dtype == 'float64':
        np_array = np_array.astype('float32')
    
    # Delete the old NumPy array if it exists
    if column in locals():
        del locals()[column]
    
    # Use the modified column name as the variable name
    globals()[column] = np_array

In [5]:
time_ctd=YYYY_MM_DD_hh_mm_ss
Lat_ctd=Latitude
Lon_ctd=Longitude
Depth_ctd=Depth_dbar
Salinity_ctd=S_SBE37
Temperature_ctd=T_SBE37_degC

In [6]:
# Read the Excel file into a pandas DataFrame
data = pd.read_excel('PALOMA_sensor_final.xlsx', header=0)

data.columns = [re.sub(r'[-%/ ]', '_', col) for col in data.columns]

for column in data.columns:
    # Convert the column to a NumPy array
    np_array = data[column].to_numpy()
    
    # Convert the data type to int32 or float32
    if np_array.dtype == 'int64':
        np_array = np_array.astype('int32')
    elif np_array.dtype == 'float64':
        np_array = np_array.astype('float32')
    
    # Delete the old NumPy array if it exists
    if column in locals():
        del locals()[column]
    
    # Use the modified column name as the variable name
    globals()[column] = np_array

In [8]:
whos

Variable              Type         Data/Info
--------------------------------------------
DO_corr_umol_kg       ndarray      19: 19 elems, type `float32`, 76 bytes
DO_raw_umol_kg        ndarray      19: 19 elems, type `float32`, 76 bytes
DO_sensor             ndarray      19: 19 elems, type `float32`, 76 bytes
Date_Time             ndarray      19: 19 elems, type `object`, 152 bytes
Depth_ctd             ndarray      319: 319 elems, type `float32`, 1276 bytes
Depth_dbar            ndarray      19: 19 elems, type `float32`, 76 bytes
Depth_sensor          ndarray      19: 19 elems, type `float32`, 76 bytes
Fixed_Station         ndarray      319: 319 elems, type `object`, 2552 bytes
Fixed_Stations        ndarray      19: 19 elems, type `object`, 152 bytes
Lat_ctd               ndarray      319: 319 elems, type `float32`, 1276 bytes
Lat_sensor            ndarray      19: 19 elems, type `float32`, 76 bytes
Latitude              ndarray      19: 19 elems, type `float32`, 76 bytes
Lon_ctd               ndarray      319: 319 elems, type `float32`, 1276 bytes
Lon_sensor            ndarray      19: 19 elems, type `float32`, 76 bytes
Longitude             ndarray      19: 19 elems, type `float32`, 76 bytes
S_SBE37               ndarray      319: 319 elems, type `float32`, 1276 bytes
S_SBE37_ODO           ndarray      19: 19 elems, type `float32`, 76 bytes
Salinity_ctd          ndarray      319: 319 elems, type `float32`, 1276 bytes
Salinity_sensor       ndarray      19: 19 elems, type `float32`, 76 bytes
T_SBE37_ODO_degC      ndarray      19: 19 elems, type `float32`, 76 bytes
T_SBE37_degC          ndarray      319: 319 elems, type `float32`, 1276 bytes
Temperature_ctd       ndarray      319: 319 elems, type `float32`, 1276 bytes
YYYY_MM_DD_hh_mm_ss   ndarray      319: 319 elems, type `object`, 2552 bytes
column                str          DO_corr_umol_kg
data                  DataFrame       Fixed_Stations        <...>213.82        220.96254
data_ctd              DataFrame        Fixed_Station  YYYY_M<...>n\n[319 rows x 7 columns]
date                  type         <class 'datetime.date'>
np                    module       <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
np_array              ndarray      19: 19 elems, type `float32`, 76 bytes
pCO2_uatm             ndarray      19: 19 elems, type `float32`, 76 bytes
pd                    module       <module 'pandas' from '/h<...>ages/pandas/__init__.py'>
re                    module       <module 're' from '/home/<...>da3/lib/python3.9/re.py'>
time_ctd              ndarray      319: 319 elems, type `object`, 2552 bytes
time_sensor           ndarray      19: 19 elems, type `object`, 152 bytes
today                 date         2023-11-01
xr                    module       <module 'xarray' from '/h<...>ages/xarray/__init__.py'>

In [9]:
time_sensor=Date_Time
Lat_sensor=Latitude
Lon_sensor=Longitude

DO_sensor=DO_corr_umol_kg
Depth_sensor=Depth_dbar
Salinity_sensor=S_SBE37_ODO
pCO2_sensor= pCO2_uatm
Temperature_sensor=T_SBE37_ODO_degC

In [18]:
# Read the Excel file into a pandas DataFrame
data = pd.read_excel('PALOMA_discrete.xlsx', header=0)
data['Datetime'] = pd.to_datetime(data['Date'].astype(str) + ' ' + data['UTC_time'].astype(str))

In [19]:
# Iterate over each column in the DataFrame

data.columns = [re.sub(r'[-%/ ]', '_', col) for col in data.columns]

for column in data.columns:
    # Convert the column to a NumPy array
    np_array = data[column].to_numpy()
    
    # Convert the data type to int32 or float32
    if np_array.dtype == 'int64':
        np_array = np_array.astype('int32')
    elif np_array.dtype == 'float64':
        np_array = np_array.astype('float32')
    
    # Delete the old NumPy array if it exists
    if column in locals():
        del locals()[column]
    
    # Use the modified column name as the variable name
    globals()[column] = np_array

In [21]:
time_aux=Datetime
Lat=Latitude
Lon=Longitude

DO_aux=DO_umol_L
DO_kg_aux=DO_umol_kg

Depth_aux=Depth_m

Fixed_Station=Fixed_Station


Salinity_aux=S_SBE37
Salinity_ODO_aux=S_SBE37_ODO


pCO2_aux= pCO2_calculated_uatm


Alkalinity= TA_umol_kg

Temperature_aux=T_SBE37_degC
Temperature_ODO_aux=T_SBE37_ODO_degC

pH_aux=_pH

T_pH_aux=T_at_pH_measurements

In [23]:
ds=xr.Dataset(
    data_vars=dict(

        Depth_ctd=(["time_ctd"], Depth_ctd,{"units": "m",
                                            "standard_name": "depth",
                                            "short_name": "depth",
                                            "long_name": "depth",
                                            "description": "depth (pressure) of sensor (dbar)",
                                            "valid_min": "0",
                                            "valid_max": "10000",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        Oxygen_discrete=(["time_aux"], DO_aux,{"units": "uatm",
                                            "standard_name": "mole_concentration_of_dissolved_molecular_oxygen_in_sea_water",
                                            "short_name": "DO",
                                            "long_name": "mole_concentration_of_dissolved_molecular_oxygen_in_sea_water",
                                            "description": "Molarity of dissolved Oxygen in sea water measured by Winkler titration.",
                                            "valid_min": "0",
                                            "valid_max": "400",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        
        Depth_discrete=(["time_aux"], Depth_aux,{"units": "m",
                                            "standard_name": "depth",
                                            "short_name": "depth",
                                            "long_name": "depth",
                                            "description": "depth from where the water sample is collected (m)",
                                            "valid_min": "0",
                                            "valid_max": "10000",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        

        Salinity_discrete=(["time_aux"], Salinity_aux,{"units": "psu",
                                            "standard_name": "sea_water_salinity",
                                            "short_name": "so",
                                            "long_name": "Sea Water Salinity",
                                            "description": "Sea water salinity is the salt content of sea water on the Practical Salinity Scale, measured by SBE37 deployed from the research vessel",
                                            "valid_min": "0",
                                            "valid_max": "100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        Salinity_ODO_discrete=(["time_aux"], Salinity_ODO_aux,{"units": "psu",
                                            "standard_name": "sea_water_salinity",
                                            "short_name": "so",
                                            "long_name": "Sea Water Salinity",
                                            "description": "salinity of the discrete water sample, measured by the SBE37-ODO sensor",
                                            "valid_min": "0",
                                            "valid_max": "100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        
        pCO2_discrete=(["time_aux"], pCO2_aux,{"units": "uatm",
                                            "standard_name": "surface_partial_pressure_of_carbon_dioxide_in_sea_water",
                                            "short_name": "pCO2",
                                            "long_name": "Surface partial pressure of carbon dioxide in sea water ",
                                            "description": " pCO2 calculated from TA and pH",
                                            "valid_min": "0",
                                            "valid_max": "1000",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        
        Alkalinity=(["time_aux"],Alkalinity,{"units": "umol/kg",
                                            "standard_name":  "sea_water_total_alkalinity",
                                            "short_name": "alkalinity",
                                            "long_name": "Sea Water Total Alkalinity",
                                            "description": "Total alkalinity sea water measured at discrete stations.",
                                            "valid_min": "0",
                                            "valid_max": "100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        
        pH_discrete=(["time_aux"],pH_aux,{"units": "pH",
                                            "standard_name":  "sea_water_pH",
                                            "short_name": "pH",
                                            "long_name": "Sea Water pH",
                                            "description": "pH measured in the lab",
                                            "valid_min": "0",
                                            "valid_max": "14",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
                

        
        Temperature_discrete=(["time_aux"], Temperature_aux,{"units": "degree Celcius",
                                            "standard_name": "sea_water_temperature",
                                            "short_name": "SW_Temperature",
                                            "long_name": "Sea Water Temperature",
                                            "description": "Sea water temperature is the in situ temperature of the sea water measured by the SBE37 deployed from the research vessel",
                                            "valid_min": "-10",
                                            "valid_max": "100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        
        Temperature_ODO_discrete=(["time_aux"], Temperature_ODO_aux,{"units": "degree Celcius",
                                            "standard_name": "sea_water_temperature",
                                            "short_name": "SW_Temperature",
                                            "long_name": "Sea Water Temperature",
                                            "description": "Sea water temperature is the in situ temperature of the sea water measured by the SBE-ODO sensor",
                                            "valid_min": "-10",
                                            "valid_max": "100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        
        
        T_pH_discrete=(["time_aux"], T_pH_aux,{"units": "degree Celcius",
                                            "standard_name": "sea_water_temperature_during_pH_measurement",
                                            "short_name": "TpH",
                                            "long_name": "Sea Water Temperature during pH measurement",
                                            "description": "temperature of the water during pH measurements",
                                            "valid_min": "-10",
                                            "valid_max": "100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        
        Oxygen=(["time_sensor"], DO_sensor,{"units": "umol/kg",
                                    "standard_name": "mole_concentration_of_dissolved_molecular_oxygen_in_sea_water",
                                    "short_name": "DO",
                                    "long_name": "mole_concentration_of_dissolved_molecular_oxygen_in_sea_water",
                                    "description": "Molarity of dissolved oxygen logged by SBE37-ODO (umol/kg)",
                                    "valid_min": "0",
                                    "valid_max": "400",
                                    "missing_value": "-9999999",
                                    "axis": "time",
                                    "history": ""}),
        Depth_ODO=(["time_sensor"], Depth_sensor,{"units": "dbar",
                                            "standard_name": "depth",
                                            "short_name": "depth",
                                            "long_name": "depth",
                                            "description": "depth (pressure) of sensor",
                                            "valid_min": "0",
                                            "valid_max": "10000",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        
        
        

        Salinity_ctd=(["time_ctd"], Salinity_ctd,{"units": "psu",
                                            "standard_name": "sea_water_salinity",
                                            "short_name": "so",
                                            "long_name": "Sea Water Salinity",
                                            "description": "Sea water salinity is the salt content of sea water on the Practical Salinity Scale, measured by SBE37 deployed from the research vessel",
                                            "valid_min": "0",
                                            "valid_max": "100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        
        Salinity_ODO=(["time_sensor"], Salinity_sensor,{"units": "psu",
                                            "standard_name": "sea_water_salinity",
                                            "short_name": "so",
                                            "long_name": "Sea Water Salinity",
                                            "description": "Sea water salinity is the salt content of sea water on the Practical Salinity Scale, measured by SBE37-ODO",
                                            "valid_min": "0",
                                            "valid_max": "100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        
        pCO2=(["time_sensor"], pCO2_sensor,{"units": "uatm",
                                    "standard_name": "surface_partial_pressure_of_carbon_dioxide_in_sea_water",
                                    "short_name": "pCO2",
                                    "long_name": "Surface partial pressure of carbon dioxide in sea water ",
                                    "description": " pCO2 in water, from Contros HydroC, corrected (uatm)",
                                    "valid_min": "0",
                                    "valid_max": "1000",
                                    "missing_value": "-9999999",
                                    "axis": "time",
                                    "history": ""}),
        
        Temperature_ODO=(["time_sensor"], Temperature_sensor,{"units": "degree Celcius",
                                    "standard_name": "sea_water_temperature",
                                    "short_name": "SW_Temperature",
                                    "long_name": "Sea Water Temperature",
                                    "description": "Sea water temperature is the in situ temperature of the sea water measured by the SBE37-ODO sensor",
                                    "valid_min": "-10",
                                    "valid_max": "100",
                                    "missing_value": "-9999999",
                                    "axis": "time",
                                    "history": ""}),

       



        Temperature_ctd=(["time_ctd"], Temperature_ctd,{"units": "degree Celcius",
                                            "standard_name": "sea_water_temperature",
                                            "short_name": "SW_Temperature",
                                            "long_name": "Sea Water Temperature",
                                            "description": "Sea water temperature is the in situ temperature of the sea water measured by the SBE37 deployed from the research vessel",
                                            "valid_min": "-10",
                                            "valid_max": "100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""})
        

    ),
    coords=dict(
    lon=(["lon"], Lon_ctd,{"units": "degrees East",
                                        "standard_name": "longitude",
                                        "short_name": "lon",
                                        "long_name": "Longitude",
                                        "description": "The Longitude represents the degrees east",
                                        "valid_min": "0",
                                        "valid_max": "360",
                                        "missing_value": "-9999999",
                                        "history": ""}),
                       
    lat=(["lat"], Lat_ctd,{"units": "degrees North",
                                        "standard_name": "latitude",
                                        "short_name": "lat",
                                        "long_name": "Latitude",
                                        "description": "The latitude represents the degrees north",
                                        "valid_min": "-90",
                                        "valid_max": "90",
                                        "missing_value": "-9999999",
                                        "history": ""}),
    time=time_ctd,
    time_sensor=time_sensor,
    time_aux=time_aux,
    reference_time=time_ctd[0],
)
)

In [24]:
ds.attrs['id']='DOI needed'

ds.attrs['naming_authority']='Istituto Nazionale di Oceanografia e Geofisica Sperimentale (OGS), Trieste, Italy '

ds.attrs['title'] = "Paloma_auxCTD"

ds.attrs['summary']='CTD and Sensor data for the PALOMA sation'
ds.attrs['keywords']='Hydrography'
ds.attrs['keywords_vocabulary']='Temperature, Salinity, Pressure'

ds.attrs['geospatial_lat_min']=np.min(Lat_sensor)
ds.attrs['geospatial_lat_max']=np.max(Lat_sensor)
ds.attrs['geospatial_lon_miN']=np.min(Lon_sensor)
ds.attrs['geospatial_lon_max']=np.max(Lon_sensor)

ds.attrs['time_coverage_start']=str(np.min(time_sensor))
ds.attrs['time_coverage_end']=str(np.max(time_sensor))

ds.attrs['Conventions']='CF 1.14'

ds.attrs['processing_level']='LEVEL 2'

ds.attrs['date_created']=str(today)

ds.attrs['creator_type']='Group'
ds.attrs['creator_institution']='Geophysical Institute'
ds.attrs['creator_name']='Joan Mateu Horrach Pou'
ds.attrs['creator_email']='joan.pou@uib.no'
ds.attrs['creator_url']=''

ds.attrs['institution']='Geophysical Institute'

ds.attrs['publisher_name']='Joan Mateu Horrach Pou'
ds.attrs['publisher_email']='joan.pou@uib.no'
ds.attrs['publisher_url']='I need the url'

ds.attrs['project']='ICOS'

ds.attrs['platform']='PALOMA'
ds.attrs['platform_vocabulary']='PALOMA_auxCTD'

ds.attrs['instrument']='SBE37'


ds.attrs['iso_topic_category']='Needed'
ds.attrs['activity_type']='in situ observation'
ds.attrs['operational_status']='active'

In [25]:
comp = dict(zlib=True, complevel=5)
encoding = {var: comp for var in ds.data_vars}
ds.to_netcdf('Paloma_CTD_sensor_discrete.nc', encoding=encoding)