In [1]:
import xarray as xr
import numpy as np
import pandas as pd
from datetime import date
today = date.today()
import re

In [6]:
# Read the Excel file into a pandas DataFrame
data = pd.read_excel('SD1030_T_S_DO_CO2_final.xlsx', header=0)
data=data.fillna(-999999)

,Platform,Date-Time,Lon,Lat,Depth_m,T_SBE_degC,S_SBE_uncorr,DO_SBE_uncorr_umol/L,RelHum_%,Press_hpa,...,DOsat_corr_%,DO_SBE_corr_umol/L,pO2,VapourPressure,ExpectedPartialPressure,gain,density,DOcorr_umol/kg,Unnamed: 20,salinity must be replaced by the corrected values
0,SD1030,2019-10-18 11:00:00,-15.312058,27.937990,0.5,22.3619,36.5131,217.16,75.63,1020.86,...,101.586807,222.551087,204.460939,27.097050,209.536767,1.024825,-999999.0,220.954240,-999999.0,-999999.0
1,SD1030,2019-10-18 12:00:00,-15.298829,27.894755,0.5,22.6058,36.6154,215.71,75.30,1020.26,...,101.547660,221.375843,204.007587,27.501345,209.366055,1.026266,-999999.0,219.835290,-999999.0,-999999.0
2,SD1030,2019-10-18 13:00:00,-15.339704,27.851370,0.5,22.4952,36.5550,217.01,74.51,1019.61,...,101.497837,221.777869,204.804424,27.317363,209.304127,1.021971,-999999.0,220.168777,-999999.0,-999999.0
3,SD1030,2019-10-18 14:00:00,-15.364848,27.806493,0.5,22.4383,36.5390,217.45,78.88,1018.65,...,101.276455,221.537699,205.014633,27.223130,208.868568,1.018798,-999999.0,220.149358,-999999.0,-999999.0
4,SD1030,2019-10-18 15:00:00,-15.381838,27.760106,0.5,22.5331,36.5827,216.15,75.96,1017.91,...,101.286810,221.132934,204.148797,27.380288,208.855066,1.023053,-999999.0,219.619907,-999999.0,-999999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6550,-999999,2020-07-17 09:00:00,13.709950,45.693344,-999999.0,21.2987,36.6913,159.88,59.07,1013.60,...,101.220606,225.769951,148.122275,25.394727,209.166617,1.412121,-999999.0,-999999.000000,-999999.0,-999999.0
6551,-999999,2020-07-17 10:00:00,13.706234,45.695379,-999999.0,21.3196,36.8138,158.10,52.95,1013.76,...,101.395850,225.913732,146.628701,25.427267,209.522055,1.428929,-999999.0,-999999.000000,-999999.0,-999999.0
6552,-999999,2020-07-17 11:00:00,13.703917,45.697008,-999999.0,21.6501,36.7244,153.63,51.17,1014.31,...,101.528014,224.986082,143.175893,25.946709,209.676387,1.464467,-999999.0,-999999.000000,-999999.0,-999999.0
6553,-999999,2020-07-17 12:00:00,13.708770,45.692909,-999999.0,21.6460,36.6266,156.31,47.40,1014.17,...,101.612904,225.319284,145.580348,25.940208,209.852599,1.441490,-999999.0,-999999.000000,-999999.0,-999999.0
6554,-999999,2020-07-17 13:00:00,13.703440,45.696768,-999999.0,21.7742,36.5827,158.06,45.85,1014.09,...,101.658635,224.961193,147.478189,26.144137,209.900476,1.423265,-999999.0,-999999.000000,-999999.0,-999999.0

In [3]:
# Iterate over each column in the DataFrame

data.columns = [re.sub(r'[-%/ ]', '_', col) for col in data.columns]

for column in data.columns:
    # Convert the column to a NumPy array
    np_array = data[column].to_numpy()
    
    # Convert the data type to int32 or float32
    if np_array.dtype == 'int64':
        np_array = np_array.astype('int32')
    elif np_array.dtype == 'float64':
        np_array = np_array.astype('float32')
    
    # Delete the old NumPy array if it exists
    if column in locals():
        del locals()[column]
    
    # Use the modified column name as the variable name
    globals()[column] = np_array

In [4]:
whos

Variable                                            Type         Data/Info
--------------------------------------------------------------------------
AirT_degC                                           ndarray      6555: 6555 elems, type `float32`, 26220 bytes
DO_SBE_corr_umol_L                                  ndarray      6555: 6555 elems, type `float32`, 26220 bytes
DO_SBE_uncorr_umol_L                                ndarray      6555: 6555 elems, type `float32`, 26220 bytes
DOcorr_umol_kg                                      ndarray      6555: 6555 elems, type `float32`, 26220 bytes
DOsat_corr__                                        ndarray      6555: 6555 elems, type `float32`, 26220 bytes
DOsat_uncorr__                                      ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Date_Time                                           ndarray      6555: 6555 elems, type `datetime64[ns]`, 52440 bytes
Depth_m                                             ndarray      6555: 6555 elems, type `float32`, 26220 bytes
ExpectedPartialPressure                             ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Lat                                                 ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Lon                                                 ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Platform                                            ndarray      6555: 6555 elems, type `object`, 52440 bytes
Press_hpa                                           ndarray      6555: 6555 elems, type `float32`, 26220 bytes
RelHum__                                            ndarray      6555: 6555 elems, type `float32`, 26220 bytes
S_SBE_uncorr                                        ndarray      6555: 6555 elems, type `float32`, 26220 bytes
T_SBE_degC                                          ndarray      6555: 6555 elems, type `float32`, 26220 bytes
Unnamed:_20                                         ndarray      6555: 6555 elems, type `float32`, 26220 bytes
VapourPressure                                      ndarray      6555: 6555 elems, type `float32`, 26220 bytes
column                                              str          salinity_must_be_replaced_by_the_corrected_values
data                                                DataFrame         Platform           D<...>n[6555 rows x 22 columns]
date                                                type         <class 'datetime.date'>
density                                             ndarray      6555: 6555 elems, type `float32`, 26220 bytes
gain                                                ndarray      6555: 6555 elems, type `float32`, 26220 bytes
np                                                  module       <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
np_array                                            ndarray      6555: 6555 elems, type `float32`, 26220 bytes
pO2                                                 ndarray      6555: 6555 elems, type `float32`, 26220 bytes
pd                                                  module       <module 'pandas' from '/h<...>ages/pandas/__init__.py'>
re                                                  module       <module 're' from '/home/<...>da3/lib/python3.9/re.py'>
salinity_must_be_replaced_by_the_corrected_values   ndarray      6555: 6555 elems, type `float32`, 26220 bytes
today                                               date         2023-07-13
xr                                                  module       <module 'xarray' from '/h<...>ages/xarray/__init__.py'>

In [7]:
time=Date_Time
Lat=Lat
Lon=Lon

Air_Temp= AirT_degC

DO= DO_SBE_corr_umol_L
DOsat= DOsat_corr__
Depth= Depth_m
Press= Press_hpa
RH=RelHum__
Salinity=S_SBE_uncorr
Temperature=T_SBE_degC
VP=VapourPressure

In [9]:
ds=xr.Dataset(
    data_vars=dict(
        
        VP=(["time"], VP,{"units": "Pa",
                                            "standard_name": "vapor_partial_pressure" ,
                                            "short_name": "vp",
                                            "long_name": "Vapor Pressure",
                                            "description": "vapour pressure calculated from T_air according to equation in Aanderaa Optode (model 4330) manual",
                                            "valid_min": "0",
                                            "valid_max": "400",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        Oxygen=(["time"], DO,{"units": "umol/L",
                                            "standard_name": "mole_concentration_of_dissolved_molecular_oxygen_in_sea_water",
                                            "short_name": "DO",
                                            "long_name": "mole_concentration_of_dissolved_molecular_oxygen_in_sea_water",
                                            "description": "Molarity of dissolved Oxygen in sea water measured by SBE37-SMP-ODO ",
                                            "valid_min": "0",
                                            "valid_max": "400",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        DO_sat=(["time"], DOsat,{"units": "uatm",
                                            "standard_name": "dissolved_molecular_oxygen_saturation_in_sea_water",
                                            "short_name": "DOsat",
                                            "long_name": "dissolved_molecular_oxygen_saturation_in_sea_water",
                                            "description": "Dissolved Oxygen saturation in sea water measured by SBE37-SMP-ODO.",
                                            "valid_min": "0",
                                            "valid_max": "400",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        
        
        Depth=(["time"], Depth,{"units": "m",
                                            "standard_name": "depth",
                                            "short_name": "depth",
                                            "long_name": "depth",
                                            "description": "depth from where the water sample is collected (m)",
                                            "valid_min": "0",
                                            "valid_max": "10000",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        RH=(["time"], RH,{"units": "%",
                                            "standard_name": "relative_humidity",
                                            "short_name": "rel_humidity",
                                            "long_name": "Relative_humidity",
                                            "description": "Air pressure is the force per unit area which would be exerted when the moving gas molecules of which the air is composed strike a theoretical surface of any orientation.",
                                            "valid_min": "800",
                                            "valid_max": "1100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        air_temperature=(["time"], Air_Temp,{"units": "K",
                                            "standard_name": "air_temperature",
                                            "short_name": "Temp",
                                            "long_name": "Temperature",
                                            "description": "Air temperature is the bulk temperature of the air",
                                            "valid_min": "-273",
                                            "valid_max": "500",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        Press=(["time"], Press,{"units": "hPa",
                                            "standard_name": "atmospheric_pressure",
                                            "short_name": "atm_press",
                                            "long_name": "Atmospheric Pressure",
                                            "description": "Atmospheric Pressure",
                                            "valid_min": "0",
                                            "valid_max": "10000",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        

        Salinity=(["time"], Salinity,{"units": "psu",
                                            "standard_name": "sea_water_salinity",
                                            "short_name": "so",
                                            "long_name": "Sea Water Salinity",
                                            "description": "Sea water salinity is the salt content of sea water on the Practical Salinity Scale, measured by SBE37 deployed from the research vessel",
                                            "valid_min": "0",
                                            "valid_max": "100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": "uncorrected"}),

        Temperature=(["time"], Temperature,{"units": "degree Celcius",
                                            "standard_name": "sea_water_temperature",
                                            "short_name": "SW_Temperature",
                                            "long_name": "Sea Water Temperature",
                                            "description": "Sea water temperature is the in situ temperature of the sea water measured by the SBE37-SMP-ODO",
                                            "valid_min": "-10",
                                            "valid_max": "100",
                                            "missing_value": "-9999999",
                                            "axis": "time",
                                            "history": ""}),
        

    ),
    coords=dict(
    lon=(["lon"], Lon,{"units": "degrees East",
                                        "standard_name": "longitude",
                                        "short_name": "lon",
                                        "long_name": "Longitude",
                                        "description": "The Longitude represents the degrees east",
                                        "valid_min": "0",
                                        "valid_max": "360",
                                        "missing_value": "-9999999",
                                        "history": ""}),
                       
    lat=(["lat"], Lat,{"units": "degrees North",
                                        "standard_name": "latitude",
                                        "short_name": "lat",
                                        "long_name": "Latitude",
                                        "description": "The latitude represents the degrees north",
                                        "valid_min": "-90",
                                        "valid_max": "90",
                                        "missing_value": "-9999999",
                                        "history": ""}),
    time=time,
    reference_time=time[0],
)
)

In [10]:


ds.attrs['id']='DOI needed'

ds.attrs['naming_authority']='NORCE Norwegian Research Centre (Norway),Istituto Nazionale di Oceanografia e Geofisica Sperimentale (Italy),Consiglio Nazionale delle Ricerche - Istituto di scienze marine (Italy),Consiglio Nazionale delle Ricerche - Istituto per lo studio degli impatti Antropici e Sostenibilità in ambiente marino (Italy),Laboratoire Océanographique de Villefranche/French National Centre for Scientific Research (France),GEOMAR Helmholtz Centre for Ocean Research Kiel (Germany) '

ds.attrs['title'] = "SD1053"

ds.attrs['summary']='SD1053 is an Autonomous Surface Vehicle (ASV) provided by the US company Saildrone. The SD1053 took part in the ATL2MED demonstration experiment from October 2019 to July 2020. During this time, the SD1053 equipped with scientific instruments sailed from the North-East Atlantic Ocean to the Gulf of Trieste in the Mediterranean Sea. A number of fixed ocean stations also took part in the experiment, e.g., DYFAMED, W1M3A, E2M3A, PALOMA, and MIRAMARE. A second ASV, SD1030, also took part in the demonstration experiment.'

ds.attrs['keywords']='Meteorology, Hydrography'
ds.attrs['keywords_vocabulary']='Temperature, Air pressure, Relative Humidity, Wind speed, Wind Direction'

ds.attrs['geospatial_lat_min']=np.min(Lat)
ds.attrs['geospatial_lat_max']=np.max(Lat)
ds.attrs['geospatial_lon_miN']=np.min(Lon)
ds.attrs['geospatial_lon_max']=np.max(Lon)

ds.attrs['time_coverage_start']=str(np.min(time))
ds.attrs['time_coverage_end']=str(np.max(time))

ds.attrs['Conventions']='CF 1.11'

ds.attrs['processing_level']='LEVEL 2'

ds.attrs['date_created']=str(today)

ds.attrs['creator_type']='Group'
ds.attrs['creator_institution']='Geophysical Institute'
ds.attrs['creator_name']='Joan Mateu Horrach Pou'
ds.attrs['creator_email']='joan.pou@uib.no'
ds.attrs['creator_url']=''

ds.attrs['institution']='Geophysical Institute'

ds.attrs['publisher_name']='Joan Mateu Horrach Pou'
ds.attrs['publisher_email']='joan.pou@uib.no'
ds.attrs['publisher_url']='I need the url'

ds.attrs['project']='ICOS'

ds.attrs['platform']='SD1053'
ds.attrs['platform_vocabulary']='Saildrone Autonomous Surface Vehicle'

ds.attrs['instrument']='Saildrone, SBE37-SMP-ODO'

ds.attrs['iso_topic_category']='Needed'
ds.attrs['activity_type']='in situ observation'
ds.attrs['operational_status']='active'

In [11]:

comp = dict(zlib=True, complevel=5)
encoding = {var: comp for var in ds.data_vars}
ds.to_netcdf('SD1053_final.nc', encoding=encoding)